@API_URL = http://localhost:5000

### Home
GET {{API_URL}}

### Books
GET {{API_URL}}/books

### Users All
GET {{API_URL}}/users

### User CREATE
POST {{API_URL}}/users
Content-Type: application/json

{
  "name": "Edward",
  "email": "ed@ed.com",
  "password": "ed123"
}
