@API_URL = http://localhost:5000

### Home
GET {{API_URL}}

### Books
GET {{API_URL}}/books

### Users All
GET {{API_URL}}/users

#### Check if I am stil logged in and give me my user info
GET {{API_URL}}/users/me

### User CREATE / SIGNUP
POST {{API_URL}}/users
Content-Type: application/json

{
  "name": "Heba",
  "email": "heba@heba.com",
  "password": "heba123"
}

### User LOGIN
POST {{API_URL}}/users/login
Content-Type: application/json

{
  "email": "heba@heba.com",
  "password": "heba12"
}

### User LOGOUT
GET {{API_URL}}/users/logout
